---
version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: certifire
      POSTGRES_PASSWORD: certifire
      POSTGRES_DB: certifire
      POSTGRES_HOST: postgres 
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  server:
    build: .
    hostname: certifire
    command: "certifire-manager runserver -h 0.0.0.0"
    privileged: true
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - ~/.aws:/root/.aws
    restart:
      always
    environment:
      DB: 'postgresql://certifire:certifire@postgres:5432/certifire'

volumes:
    pg_data: {}