"""empty message

Revision ID: 680515b00e83
Revises: 3dc6f28a2339
Create Date: 2021-04-11 15:26:32.781189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680515b00e83'
down_revision = '3dc6f28a2339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('no_check', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'no_check')
    # ### end Alembic commands ###
